# Generated by Django 4.2 on 2023-04-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0002_remove_pereval_height_remove_pereval_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pereval',
            name='level_autumn',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_spring',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_summer',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='level_winter',
        ),
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.CharField(blank=True, choices=[('1A', '1A'), ('1Б', '1Б'), ('2А', '2А'), ('2Б', '2Б'), ('3А', '3А'), ('3Б', '3Б')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pereval',
            name='weather',
            field=models.CharField(blank=True, choices=[('winter', 'зима'), ('spring', 'весна'), ('summer', 'лето'), ('autumn', 'осень')], max_length=10, null=True),
        ),
    ]
