# Generated by Django 4.2 on 2023-04-06 17:29

from django.db import migrations, models
import pereval_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0004_alter_pereval_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=pereval_app.models.pereval_directory_path),
        ),
    ]
