# Generated by Django 4.2 on 2023-04-09 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval_app', '0005_alter_images_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='coords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coords_pereval', to='pereval_app.coords'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pereval', to=settings.AUTH_USER_MODEL),
        ),
    ]
